seed: 4
num_workers: 6
submit: True
useval: False
each: False
batch_size: 4096
max_epochs: 550
min_epochs: 550
patience: 0
val_check: 1.0
over_sample: True
objective: 'train_loss'
n_hidden: 16
use_prices: False
dist: 'StudentT'
df: 5
dropout: 0.1
optimizer: 'Adam'
lr: 0.001
weight_decay: 0.0
scheduler: 'None'
T_max: 100
use_te: True
