seed: 1
num_workers: 12
submit: True
useval: True
each: True
batch_size: 4096
max_epochs: 10
min_epochs: 10
patience: 0
val_check: 0.1
over_sample: True
objective: 'train_wloss'
n_hidden: 16
use_prices: True
dist: 'NegativeBinomial'
df: 1
dropout: 0.1
optimizer: 'Adam'
lr: 0.001
weight_decay: 0.001
scheduler: 'None'
T_max: 100
use_te: True
